### PR TITLE
Update ev3.py

### PR DESCRIPTION
**Pull request by Pedro-Beirao**
Different USB handling based on OS. This just checks the current OS, if its MacOS, it handles USB with hidapi. 

What I did is a bit lazy. It checks the OS every time it sends or receives data. I don't think it affects performance though.

Also included the changes that *windoze* made on the #2 pull request.

### CODE REVIEW

**Review by ChristophGaukel — APPROVED** [review]
Hallo,
thank you for this request. I will merge it. I also did prepare a next version, which follows the same, your idea. Your request is an improvement, but:
- system commands need the same distinction.
- Your version does not allow to connect and use multiple EV3 devices parallel. Your solution with globals does not support this any more.
I hope to pull this version  tomorrow.
Kind regards,
Christoph

**Comment by Pedro-Beirao** [comment]
@ChristophGaukel 

Hi.
On ev3.py, in line 20 `from .exceptions import NoEV3,  DirCmdError, SysCmdError`
On exceptions.py the is no NoEV3 definition.

Error:`cannot import name 'NoEV3' from 'ev3_dc.exceptions'`

Besides that, the new version is working great on MacOS 👍 (Much better than global variables)

Regards
Pedro

**Comment by ChristophGaukel** [comment]
Hi Pedro,
I prefer specific exceptions because they allow to handle specific error situations (with try - except - blocks). Therefore I introduced exception NoEV3, which is raised when no EV3 device has been found or not the specified one.

You find the additional exception classes in file exceptions.py and I wonder that your program does not find class NoEV3. May it be, that you combine a newer version of file ev3.py with an older version of file exceptions.py?

Besides that, thanks for your positive feedback.

Kind regards,
Christoph

**Comment by Pedro-Beirao** [comment]
Hi
You are right, I had an older version of exceptions.py
Thanks
Regards
Pedro

**Pull request merged**
