### PR TITLE
Documentation of ev3_dc.Gyro

### PR DESCRIPTION
**Pull request by Jackomatrus**
I included a simple program. I've never written docs before and have no idea of .rst formatting, so please excuse any errors.

### CODE REVIEW

**Comment by ChristophGaukel** [comment]
Hi,
thanks, I did merge it directly. Yesterday, I took a look at your code. Up to now only the angle (mode EV3-Gyro-Angle) is realized. I think, it needs also modes EV3-Gyro-Rate and EV3-Gyro-Rate & Angle. Tell me, if you like to add it. If not, I will do it.

Once again: great, really great!

Kind regards
Christoph

**Comment by Jackomatrus** [comment]
As I have no idea about the ev3's communication protocol (I only implemented Angle by copy-pasting your code), I'd have to pass on this one 🙂
Best regards,
Jamin

**Comment by ChristophGaukel** [comment]
Hi Jamin,
I have done some small modifications in your documentation (it needs to reside in the source-directory, I follow some naming conventions, your class must also be referenced in the API documentation). Now you can see your text in readthedocs.

I will add the modes soon.

Kind regards,
Christoph

**Comment by ChristophGaukel** [comment]
Hi Jamin,
I added the measurement of rate (angular velocity) and a bit more. Changing the mode resets the angle, this is why all measurements are done with mode 3 (EV3-Gyro-Rate & Angle) now. I hope it works fine. This version also is on pypi.

Kind regards,
Christoph

**Comment by Jackomatrus** [comment]
Thank you very much for taking the time to add this functionality

**Pull request merged**
